ecomprj/core/urls.py
from django.urls import path,include
from core import views
from userauths.views import ajax_contact_page_view
app_name='core'

urlpatterns=[
    path("",views.index, name="index"),
    path('products/',views.product_list_view,name='product-list'),
    path('product/<pid>',views.product_details_view,name='product-details-page'),
    path('category/',views.category_list_view,name='category-list'),
    path('category/<cid>',views.category_product_list_view,name='category_product_list_view'),
    path('vendors/',views.vendor_list_view,name='vendor-list-view'),
    path('vendors/<vid>', views.vendor_details_view,name='vendor-details-page'),
    path('products/tag/<tag_slug>/',views.tag_list,name='tags'),
    path('ajax-add-review/<pid>',views.ajax_add_review,name='ajax-add-review'),
    path('search/',views.search_view,name='search'),
    path('filter-products/',views.filter_product,name='filter-product'),
    path('add-to-cart/',views.add_cart_view,name='add-to-cart'),
    path('cart/',views.cart_view,name='cart'),
    path('delete-from-cart/',views.delete_product_from_cart,name='delete-from-cart'),
    path('update-cart/',views.update_from_cart,name='update-from-cart'),
    path('checkout/',views.checkout_view,name='checkout'),
    path('paypal/',include('paypal.standard.ipn.urls')),
    path('payment-completed/<oid>',views.payment_completed_view,name='payment-completed'),
    path('payment-failed/',views.payment_failed_view,name='payment-failed'),
    path('dashboard/',views.customer_dashboard,name='dashboard'),
    path('order-details/<id>',views.order_details_view,name='order-details'),
    path('make-default-address/',views.make_address_default,name='make-default-address'),
    path('add-to-wishlist/',views.add_to_wishlist,name='add-to-wishlist'),
    path('wishlist/',views.wishlist_view,name='wishlist'),
    path('remove-from-wishlist/',views.remove_from_wishlist_view,name='remove-from-wishlist'),
    path('ajax-contact-form/',ajax_contact_page_view,name='ajax-contact-form'),
    path('save-checkout-info/',views.save_checkout_info_view,name='save-checkout-info'),
    path('checkout/<oid>',views.checkout_view,name='checkout')
]

ecomprj/ecomprj/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("core.urls")),
    path("user/", include("userauths.urls")),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path("useradmin/", include("useradmin.urls")),
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ecomprj/core/forms.py
from django import forms
from core.models import ProductReview

class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder':'enter your review'}))

    class Meta:
        model = ProductReview
        fields = ['review','rating']
        

ecomprj/core/views.py
from django.http import HttpResponse, JsonResponse
from django.db.models import Avg, Count
from django.shortcuts import get_object_or_404, redirect, render
from django.db.models.functions import ExtractMonth
from taggit.models import Tag
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from paypal.standard.forms import PayPalPaymentsForm
from django.contrib import messages
from django.template.loader import render_to_string
from django.core import serializers
from core.forms import ProductReviewForm
import calendar
from userauths.models import Profile
from core.models import Product,Vendor,Category,Coupons,ProductImage,ProductReview,CartOrder,CartOrderItems,Wishlist,Address
def index(request):
    # products = Product.objects.all().order_by('-date')
    products = Product.objects.filter(featured=True, product_status='published')
    context={
        'products':products
    }
    return render(request,'core/index.html',context)

def product_list_view(request):
    products = Product.objects.filter(product_status='published')
    context={
        'products':products
    }
    return render(request,'core/product-list.html',context)

def category_list_view(request):
    categories = Category.objects.all()
    context={
        'categories':categories
    }
    return render(request, 'core/category-list.html', context)

def category_product_list_view(request,cid):
    category = Category.objects.get(cid=cid)
    products = Product.objects.filter(product_status = 'published',category=category)
    context={
        'category':category,
        'products':products
    }
    return render(request,'core/category-product-list.html',context)

def vendor_list_view(request):
    vendors = Vendor.objects.all()
    context={
        'vendors':vendors
    }
    return render (request,'core/vendor-list.html',context)

def vendor_details_view(request,vid):
    vendor = Vendor.objects.get(vid=vid)
    products = Product.objects.filter(product_status='published',vendor=vendor)
    context={
        'products':products,
        'vendor':vendor
    }
    return render(request,'core/vendor-details-view.html',context)

def product_details_view(request,pid):
    product = Product.objects.get(pid=pid)
    product_images = product.p_image.all()
    make_review=True

    if request.user.is_authenticated:
        review_count = ProductReview.objects.filter(product=product,user=request.user).count()
        if review_count > 0:
            make_review = False
    products  = Product.objects.filter(category = product.category).exclude(pid=pid)
    reviews = ProductReview.objects.filter(product=product).order_by('-date')
    #getting average rating
    average_rating = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))
    ratings_form = ProductReviewForm()
    context = {
        'product':product,
        'make_review': make_review,
        'product_images':product_images,
        'ratings_form':ratings_form,
        'average_rating':average_rating,
        'related_products':products,
        'reviews':reviews

    }
    return render(request,'core/product-details-page.html',context)

def tag_list(request,tag_slug=None):
    products = Product.objects.filter(product_status='published').order_by('-id')
    tag = None
    if tag_slug:
        tag=get_object_or_404(Tag,slug=tag_slug)
        products = products.filter(tags__in=[tag])
    context={
        'products':products,
        'tags':tag
    }
    return render(request,'core/tags.html',context)

def ajax_add_review(request,pid):
    product  = Product.objects.get(pid=pid)
    user=request.user
    review = ProductReview.objects.create(
        user=user,
        product= product,
        review = request.POST['review'],
        rating=request.POST['rating']
    )
    context={
        'user':user.username,
        'review': request.POST['review'],
        'rating':request.POST['rating']
    }

    average_rating = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))

    return JsonResponse(
        {
            'bool':True,
            'context':context,
            'average_rating':average_rating
        }
    )

def search_view(request):
    query = request.GET['q']
    products = Product.objects.filter(title__icontains=query).order_by('-date')
    context={
        'products':products,
        'query':query
    }
    return render(request,'core/search.html',context)

def filter_product(request):
    categories = request.GET.getlist('category[]')
    vendors = request.GET.getlist('vendor[]')
    min_price = request.GET['min_price']
    max_price = request.GET['max_price']
    products = Product.objects.filter(product_status='published').order_by('-id').distinct()
    products = products.filter(price__gte=min_price)
    products = products.filter(price__lte=max_price)

    if len(categories)>0:
        products = products.filter(category__id__in = categories).distinct()
    if len(vendors)>0:
        vendors = products.filter(vendor__id__in = vendors).distinct()

    data = render_to_string('core/async/product-list.html',{'products':products})
    return JsonResponse({
        'data':data
    })

def add_cart_view(request):
    vendor = Vendor.objects.get(id=request.GET['vendor'])
    cart_product={}
    cart_product[str(request.GET['id'])]={
        'title':request.GET['title'],
        'quantity':request.GET['quantity'],
        'price':request.GET['price'],
        'pid':request.GET['pid'],
        'image': request.GET['image'],
        'vendor':vendor.id
    }

    if 'cart_data_obj' in request.session:
        if str(request.GET['id']) in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['quantity']+=int(cart_product[str(request.GET['id'])]['quantity'])
            cart_data.update(cart_data)
            request.session['cart_data_obj']=cart_data
        else:
            cart_data = request.session['cart_data_obj']
            cart_data.update(cart_product)
            request.session['cart_data_obj'] = cart_data
    else:
        request.session['cart_data_obj'] = cart_product

    return JsonResponse({
        'data':request.session['cart_data_obj'],
        'totalcartitems':len(request.session['cart_data_obj'])
    })

def cart_view(request):
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount+= int(item['quantity'])*float(item['price'])
        return render(request,'core/cart.html',{'cart_data':request.session['cart_data_obj'],
        'totalcartitems':len(request.session['cart_data_obj']),'cart_total_amount':cart_total_amount})
    else:
       messages.warning(request,'Your cart is empty')
       return redirect('core:index')
    

def delete_product_from_cart(request):
    product_id=str(request.GET['id'])
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data  = request.session['cart_data_obj']
            del request.session['cart_data_obj'][product_id]
            request.session['cart_data_obj'] = cart_data
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount+= int(item['quantity'])*float(item['price'])
        
    context = render_to_string('core/async/cart-list.html',{'cart_data':request.session['cart_data_obj'],
        'totalcartitems':len(request.session['cart_data_obj']),'cart_total_amount':cart_total_amount})
    return JsonResponse({'data':context,'totalcartitems':len(request.session['cart_data_obj'])})

def update_from_cart(request):
    product_id=str(request.GET['id'])
    product_quantity = request.GET['quantity']
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data  = request.session['cart_data_obj']
            cart_data[product_id]['quantity']=product_quantity
            request.session['cart_data_obj'] = cart_data
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount+= int(item['quantity'])*float(item['price'])
        
    context = render_to_string('core/async/cart-list.html',{'cart_data':request.session['cart_data_obj'],
        'totalcartitems':len(request.session['cart_data_obj']),'cart_total_amount':cart_total_amount})
    return JsonResponse({'data':context,'totalcartitems':len(request.session['cart_data_obj'])})

def save_checkout_info_view(request):
    cart_total_amount = 0
    total_amount=0
    if request.method=='POST':
        full_name = request.POST['full_name']
        email=request.POST['email']
        mobile = request.POST['mobile']
        address = request.POST['address']
        city = request.POST['city']
        state = request.POST['state']
        country = request.POST['country']
        request.session['full_name']=full_name
        request.session['email']=email
        request.session['mobile']=mobile
        request.session['address']=address
        request.session['city']=city
        request.session['state']=state
        request.session['country']=country

    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            total_amount+= int(item['quantity'])*float(item['price'])
        order = CartOrder.objects.create(
            user=request.user,
            full_name=request.session['full_name'],
            email=request.session['email'],
            mobile=request.session['mobile'],
            address=request.session['address'],
            city=request.session['city'],

ecomprj/templates/core/async/cart-list.html
<main class="main" id="cart-list">
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="/" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                <span></span> Shop
                <span></span> Cart
            </div>
        </div>
    </div>
    <div class="container mb-80 mt-50">
        <div class="row">
            <div class="col-lg-8 mb-40">
                <h1 class="heading-2 mb-10">Your Cart</h1>
                <div class="d-flex justify-content-between">
                    <h6 class="text-body">There are <span class="text-brand">{{ totalcartitems }}</span> products in your cart</h6>
                </div>
            </div>
        </div>
        <form action="{%url 'core:save-checkout-info'%}" method="POST">
            {% csrf_token%}
            <div class="row">
                <div class="col-lg-8">
                    <div class="table-responsive shopping-summery">
                        <table class="table table-wishlist">
                            <thead>
                                <tr class="main-heading">
                                    
                                    <th scope="col">Product</th>
                                    <th scope="col">Title</th>
                                    <th scope="col">Unit Price</th>
                                    <th scope="col" class="text-center">Quantity</th>
                                    <th scope="col">Subtotal</th>
                                    <th scope="col" class="">Refresh</th>
                                    <th scope="col" class="end">Remove</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for product_id, item in cart_data.items %}
                                <tr class="pt-30">
                                    <td class="image product-thumbnail pt-40"><img src="{{ item.image }}" alt="#"></td>
                                    <td class="product-des product-name">
                                        <h6 class="mb-5"><a class="product-name mb-10 text-heading" href="{% url 'core:product-details-page' item.pid %}">{{ item.title }}</a></h6>
                                    
                                    </td>
                                    <td class="price" data-title="Price">
                                        <h4 class="text-body">${{item.price|floatformat:2}}</h4>
                                    </td>
                                    <td class="text-center detail-info" data-title="Stock">
                                        <div class="mr-15">
                                            <input type="number" placeholder="Qty" class="w-25 product-quantity-{{ product_id }}"  name="" value="{{ item.quantity }}" id="">
                                        </div>
                                    </td>
                                    <td class="price" data-title="Price">
                                        <h4 class="text-brand">${% widthratio item.price 1 item.quantity %} </h4>
                                    </td>
                                    <td class="action text-center" data-title="Remove"><a style="border: none; background: none;"  class="text-body update-product" data-product="{{ product_id }}"><i class="fi-rs-refresh"></i></a></td>
                                    <td class="action text-center" data-title="Remove"><a style="border: none; background: none;"  class="text-body delete-product" data-product="{{ product_id }}"><i class="fi-rs-trash"></i></a></td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>

                        <div class="row mt-4">
                            <h4 class="mb-30">Bio Data</h4>
                            <div class="row">
                                <div class="form-group col-lg-12">
                                    <label for="">Full Name</label>
                                    <input type="text" required="" name="full_name" value="" placeholder="Full Name">
                                </div>
                                <div class="form-group col-lg-6">
                                    <label for="">Email</label>
                                    <input type="text" required="" name="email"  placeholder="mobile *" value="">
                                </div>
                                <div class="form-group col-lg-6">
                                    <label for="">Mobile</label>
                                    <input type="text" name="mobile" value="" required="" placeholder="Address *">
                                </div>
                            </div>
                            <h4 class="mb-30">Shipping Details</h4>
                            <div class="row">
                                <div class="form-group col-lg-6">
                                    <label for="">Address</label>
                                    <input type="text" name="address" value="" placeholder="Address">
                                </div>
                                <div class="form-group col-lg-6">
                                    <label for="">City</label>
                                    <input type="text" name="city"  placeholder="City *" value="">
                                </div>
                                <div class="form-group col-lg-6">
                                    <label for="">State</label>
                                    <input type="text" name="state" value="" placeholder="State *">
                                </div>
                                <div class="form-group col-lg-6">
                                    <label for="">Country</label>
                                    <input type="text" name="country" value="" placeholder="Country *">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="border p-md-4 cart-totals ml-30">
                        <div class="table-responsive">
                            <div>
                                <div class="d-flex justify-content-between mb-2">
                                    <p class="fw-bold">Tax</p>
                                    <p>$0</p>
                                </div>
                                <div class="d-flex justify-content-between mb-2">
                                    <p class="fw-bold">Shipping</p>
                                    <p>$0</p>
                                </div>
                                <div class="d-flex justify-content-between mb-2">
                                    <p class="fw-bold">Discount</p>
                                    <p>$0</p>
                                </div>
                                
                                <div class="d-flex justify-content-between mb-2">
                                    <p class="fw-bold">Total</p>
                                    <p>${{cart_total_amount}}</p>
                                </div>
                            </div>
                        </div>
                        {% if totalcartitems %}
                            <button type="submit" class="btn mb-20 w-100">Proceed To CheckOut<i class="fi-rs-sign-out ml-15"></i></button>
                        {% endif %}                    
                    </div>
                </div>
            </div>
        </form>
    </div>
</main>

ecomprj/templates/core/async/product-list.html
{% for p in products %}
<div class="col-lg-1-5 col-md-4 col-12 col-sm-6">
    <div class="product-cart-wrap mb-30 wow animate__animated animate__fadeIn" data-wow-delay=".1s">
        <div class="product-img-action-wrap">
            <div class="product-img product-img-zoom">
                <a href="{% url 'core:product-details-page' p.pid %}">
                    <img class="default-img" src="{{p.image.url}}" alt="" />
                    <img class="hover-img" src="{{p.image.url}}" alt="" />
                </a>
            </div>
            <div class="product-action-1">
                <a aria-label="Add To Wishlist" class="action-btn" href="shop-wishlist.html"><i class="fi-rs-heart"></i></a>
                <a aria-label="Compare" class="action-btn" href="shop-compare.html"><i class="fi-rs-shuffle"></i></a>
                <a aria-label="Quick view" class="action-btn" data-bs-toggle="modal" data-bs-target="#quickViewModal"><i class="fi-rs-eye"></i></a>
            </div>
            <div class="product-badges product-badges-position product-badges-mrg">
                <span class="hot">{{p.get_percentage|floatformat:0}}%</span>
            </div>
        </div>
        <div class="product-content-wrap">
            <div class="product-category">
                <a href="{% url 'core:category_product_list_view' p.category.cid %}">{{p.category.title}}</a>
            </div>
            <h2><a href="{% url 'core:product-details-page' p.pid %}">{{p.title}}</a></h2>
            <div class="product-rate-cover">
                <div class="product-rate d-inline-block">
                    <div class="product-rating" style="width: 90%"></div>
                </div>
                <span class="font-small ml-5 text-muted"> (4.0)</span>
            </div>
            <div>
                <span class="font-small text-muted">By <a href="{% url 'core:vendor-details-page' p.vendor.vid %}">{{p.vendor.title}}</a></span>
            </div>
            <div class="product-card-bottom">
                <div class="product-price">
                    <span>{{p.price}}</span>
                    <span class="old-price">${{p.old_price}}</span>
                </div>
                <div class="add-cart">
                    <a class="add" href="shop-cart.html"><i class="fi-rs-shopping-cart mr-5"></i>Add </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor%}

ecomprj/templates/core/async/wishlist.html
{%extends 'partials/base.html'%}
{%load static%}
{%block content%}

    <main class="main wishlist-test">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Shop <span></span> Fillter
                </div>
            </div>
        </div>
        <div class="container mb-30 mt-50">
            <div class="row">
                <div class="col-xl-10 col-lg-12 m-auto">
                    <div class="mb-50">
                        <h1 class="heading-2 mb-10">Your Wishlist</h1>
                        <h6 class="text-body">There are <span class="text-brand">{{wishlist.count}}</span> products in this list</h6>
                    </div>
                    <div class="table-responsive shopping-summery">
                        <table class="table table-wishlist">
                            <thead>
                                <tr class="main-heading">
                                    <th class="custome-checkbox start pl-30">
                                        <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox11" value="" />
                                        <label class="form-check-label" for="exampleCheckbox11"></label>
                                    </th>
                                    <th scope="col" colspan="2">Product</th>
                                    <th scope="col">Price</th>
                                    <th scope="col">Stock Status</th>
                                    <th scope="col">Action</th>
                                    <th scope="col" class="end">Remove</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for w in wishlist%}
                                <tr class="pt-30">
                                    <td class="custome-checkbox pl-30">
                                        <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox1" value="" />
                                        <label class="form-check-label" for="exampleCheckbox1"></label>
                                    </td>
                                    <td class="image product-thumbnail pt-40"><img src="{{w.product.image.url}}" alt="#" /></td>
                                    <td class="product-des product-name">
                                        <h6><a class="product-name mb-10" href="{% url 'core:product-details-page' w.product.pid %}">{{w.product.title}}</a></h6>
                                        <div class="product-rate-cover">
                                            <div class="product-rate d-inline-block">
                                                <div class="product-rating" style="width: 90%"></div>
                                            </div>
                                            <span class="font-small ml-5 text-muted"> (4.0)</span>
                                        </div>
                                    </td>
                                    <td class="price" data-title="Price">
                                        <h3 class="text-brand">${{w.product.price}}</h3>
                                    </td>
                                    <td class="text-center detail-info" data-title="Stock">
                                        <span class="stock-status in-stock mb-0"> {%if w.product.in_stock %}In Stock{%else%}Out Of Stock{%endif%} </span>
                                    </td>
                                    <td class="text-right" data-title="Cart">
                                        <div class="add-cart">
                                            <input name='' id='product-quantity' value='1' type='hidden' class='product-quantity-{{w.product.id}}'>
                                            <input name='' id='' class='product-pid-{{w.product.id}}' type='hidden' value='{{w.product.pid}}'>
                                            <input name='' id='' class='product-title-{{w.product.id}}' type='hidden' value='{{w.product..title}}'>
                                            <input name=''  id='' class='product-image-{{w.product.id}}' value='{{w.product..image.url}}' type='hidden'>
                                            <input name='' id='' class='product-id-{{w.product.id}}' value='{{w.product.id}}' type='hidden'>
                                            <button class="add add-to-cart-btn btn" id='add-to-cart-btn' data-index='{{w.product.id}}'>Add to Cart</button>
                                            
                                        </div>
                                    </td>
                                    <td class="action text-center" data-title="Remove">
                                        <button style='border:none;background:none' data-product-id='{{w.product.id}}' class="text-body remove-btn remove-btn-{{w.product.id}}"><i class="fi-rs-trash"></i></button>
                                    </td>
                                </tr>
                                {%endfor%}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </main>
{%endblock content%}