ecomprj/core/urls.py
from django.urls import path,include
from core import views
from userauths.views import ajax_contact_page_view
app_name='core'

urlpatterns=[
    path("",views.index, name="index"),
    path('products/',views.product_list_view,name='product-list'),
    path('product/<pid>',views.product_details_view,name='product-details-page'),
    path('category/',views.category_list_view,name='category-list'),
    path('category/<cid>',views.category_product_list_view,name='category_product_list_view'),
    path('vendors/',views.vendor_list_view,name='vendor-list-view'),
    path('vendors/<vid>', views.vendor_details_view,name='vendor-details-page'),
    path('products/tag/<tag_slug>/',views.tag_list,name='tags'),
    path('ajax-add-review/<pid>',views.ajax_add_review,name='ajax-add-review'),
    path('search/',views.search_view,name='search'),
    path('filter-products/',views.filter_product,name='filter-product'),
    path('add-to-cart/',views.add_cart_view,name='add-to-cart'),
    path('cart/',views.cart_view,name='cart'),
    path('delete-from-cart/',views.delete_product_from_cart,name='delete-from-cart'),
    path('update-cart/',views.update_from_cart,name='update-from-cart'),
    path('checkout/',views.checkout_view,name='checkout'),
    path('paypal/',include('paypal.standard.ipn.urls')),
    path('payment-completed/<oid>',views.payment_completed_view,name='payment-completed'),
    path('payment-failed/',views.payment_failed_view,name='payment-failed'),
    path('dashboard/',views.customer_dashboard,name='dashboard'),
    path('order-details/<id>',views.order_details_view,name='order-details'),
    path('make-default-address/',views.make_address_default,name='make-default-address'),
    path('add-to-wishlist/',views.add_to_wishlist,name='add-to-wishlist'),
    path('wishlist/',views.wishlist_view,name='wishlist'),
    path('remove-from-wishlist/',views.remove_from_wishlist_view,name='remove-from-wishlist'),
    path('ajax-contact-form/',ajax_contact_page_view,name='ajax-contact-form'),
    path('save-checkout-info/',views.save_checkout_info_view,name='save-checkout-info'),
    path('checkout/<oid>',views.checkout_view,name='checkout')
]

ecomprj/ecomprj/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("core.urls")),
    path("user/", include("userauths.urls")),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path("useradmin/", include("useradmin.urls")),
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ecomprj/userauths/urls.py
from django.urls import path
from userauths import views

app_name='userauths'
urlpatterns = [
    path('sign-up/', views.register_view, name='sign-up'),
    path('sign-in/',views.login_view, name='sign-in'),
    path('sign-out/',views.logout_view, name='sign-out'),
    path('edit-profile',views.edit_profile_view,name='edit-profile'),
    path('contact/',views.contact_views,name='contact-us'),
]

ecomprj/core/forms.py
from django import forms
from core.models import ProductReview

class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder':'enter your review'}))

    class Meta:
        model = ProductReview
        fields = ['review','rating']
        

ecomprj/core/views.py
from django.http import HttpResponse, JsonResponse
from django.db.models import Avg, Count
from django.shortcuts import get_object_or_404, redirect, render
from django.db.models.functions import ExtractMonth
from taggit.models import Tag
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from paypal.standard.forms import PayPalPaymentsForm
from django.contrib import messages
from django.template.loader import render_to_string
from django.core import serializers
from core.forms import ProductReviewForm
import calendar
from userauths.models import Profile
from core.models import Product,Vendor,Category,Coupons,ProductImage,ProductReview,CartOrder,CartOrderItems,Wishlist,Address
def index(request):
    # products = Product.objects.all().order_by('-date')
    products = Product.objects.filter(featured=True, product_status='published')
    context={
        'products':products
    }
    return render(request,'core/index.html',context)

def product_list_view(request):
    products = Product.objects.filter(product_status='published')
    context={
        'products':products
    }
    return render(request,'core/product-list.html',context)

def category_list_view(request):
    categories = Category.objects.all()
    context={
        'categories':categories
    }
    return render(request, 'core/category-list.html', context)

def category_product_list_view(request,cid):
    category = Category.objects.get(cid=cid)
    products = Product.objects.filter(product_status = 'published',category=category)
    context={
        'category':category,
        'products':products
    }
    return render(request,'core/category-product-list.html',context)

def vendor_list_view(request):
    vendors = Vendor.objects.all()
    context={
        'vendors':vendors
    }
    return render (request,'core/vendor-list.html',context)

def vendor_details_view(request,vid):
    vendor = Vendor.objects.get(vid=vid)
    products = Product.objects.filter(product_status='published',vendor=vendor)
    context={
        'products':products,
        'vendor':vendor
    }
    return render(request,'core/vendor-details-view.html',context)

def product_details_view(request,pid):
    product = Product.objects.get(pid=pid)
    product_images = product.p_image.all()
    make_review=True

    if request.user.is_authenticated:
        review_count = ProductReview.objects.filter(product=product,user=request.user).count()
        if review_count > 0:
            make_review = False
    products  = Product.objects.filter(category = product.category).exclude(pid=pid)
    reviews = ProductReview.objects.filter(product=product).order_by('-date')
    #getting average rating
    average_rating = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))
    ratings_form = ProductReviewForm()
    context = {
        'product':product,
        'make_review': make_review,
        'product_images':product_images,
        'ratings_form':ratings_form,
        'average_rating':average_rating,
        'related_products':products,
        'reviews':reviews

    }
    return render(request,'core/product-details-page.html',context)

def tag_list(request,tag_slug=None):
    products = Product.objects.filter(product_status='published').order_by('-id')
    tag = None
    if tag_slug:
        tag=get_object_or_404(Tag,slug=tag_slug)
        products = products.filter(tags__in=[tag])
    context={
        'products':products,
        'tags':tag
    }
    return render(request,'core/tags.html',context)

def ajax_add_review(request,pid):
    product  = Product.objects.get(pid=pid)
    user=request.user
    review = ProductReview.objects.create(
        user=user,
        product= product,
        review = request.POST['review'],
        rating=request.POST['rating']
    )
    context={
        'user':user.username,
        'review': request.POST['review'],
        'rating':request.POST['rating']
    }

    average_rating = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))

    return JsonResponse(
        {
            'bool':True,
            'context':context,
            'average_rating':average_rating
        }
    )

def search_view(request):
    query = request.GET['q']
    products = Product.objects.filter(title__icontains=query).order_by('-date')
    context={
        'products':products,
        'query':query
    }
    return render(request,'core/search.html',context)

def filter_product(request):
    categories = request.GET.getlist('category[]')
    vendors = request.GET.getlist('vendor[]')
    min_price = request.GET['min_price']
    max_price = request.GET['max_price']
    products = Product.objects.filter(product_status='published').order_by('-id').distinct()
    products = products.filter(price__gte=min_price)
    products = products.filter(price__lte=max_price)

    if len(categories)>0:
        products = products.filter(category__id__in = categories).distinct()
    if len(vendors)>0:
        vendors = products.filter(vendor__id__in = vendors).distinct()

    data = render_to_string('core/async/product-list.html',{'products':products})
    return JsonResponse({
        'data':data
    })

def add_cart_view(request):
    vendor = Vendor.objects.get(id=request.GET['vendor'])
    cart_product={}
    cart_product[str(request.GET['id'])]={
        'title':request.GET['title'],
        'quantity':request.GET['quantity'],
        'price':request.GET['price'],
        'pid':request.GET['pid'],
        'image': request.GET['image'],
        'vendor':vendor.id
    }

    if 'cart_data_obj' in request.session:
        if str(request.GET['id']) in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['quantity']+=int(cart_product[str(request.GET['id'])]['quantity'])
            cart_data.update(cart_data)
            request.session['cart_data_obj']=cart_data
        else:
            cart_data = request.session['cart_data_obj']
            cart_data.update(cart_product)
            request.session['cart_data_obj'] = cart_data
    else:
        request.session['cart_data_obj'] = cart_product

    return JsonResponse({
        'data':request.session['cart_data_obj'],
        'totalcartitems':len(request.session['cart_data_obj'])
    })

def cart_view(request):
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount+= int(item['quantity'])*float(item['price'])
        return render(request,'core/cart.html',{'cart_data':request.session['cart_data_obj'],
        'totalcartitems':len(request.session['cart_data_obj']),'cart_total_amount':cart_total_amount})
    else:
       messages.warning(request,'Your cart is empty')
       return redirect('core:index')
    

def delete_product_from_cart(request):
    product_id=str(request.GET['id'])
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data  = request.session['cart_data_obj']
            del request.session['cart_data_obj'][product_id]
            request.session['cart_data_obj'] = cart_data
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount+= int(item['quantity'])*float(item['price'])
        
    context = render_to_string('core/async/cart-list.html',{'cart_data':request.session['cart_data_obj'],
        'totalcartitems':len(request.session['cart_data_obj']),'cart_total_amount':cart_total_amount})
    return JsonResponse({'data':context,'totalcartitems':len(request.session['cart_data_obj'])})

def update_from_cart(request):
    product_id=str(request.GET['id'])
    product_quantity = request.GET['quantity']
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data  = request.session['cart_data_obj']
            cart_data[product_id]['quantity']=product_quantity
            request.session['cart_data_obj'] = cart_data
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount+= int(item['quantity'])*float(item['price'])
        
    context = render_to_string('core/async/cart-list.html',{'cart_data':request.session['cart_data_obj'],
        'totalcartitems':len(request.session['cart_data_obj']),'cart_total_amount':cart_total_amount})
    return JsonResponse({'data':context,'totalcartitems':len(request.session['cart_data_obj'])})

def save_checkout_info_view(request):
    cart_total_amount = 0
    total_amount=0
    if request.method=='POST':
        full_name = request.POST['full_name']
        email=request.POST['email']
        mobile = request.POST['mobile']
        address = request.POST['address']
        city = request.POST['city']
        state = request.POST['state']
        country = request.POST['country']
        request.session['full_name']=full_name
        request.session['email']=email
        request.session['mobile']=mobile
        request.session['address']=address
        request.session['city']=city
        request.session['state']=state
        request.session['country']=country

    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            total_amount+= int(item['quantity'])*float(item['price'])
        order = CartOrder.objects.create(
            user=request.user,
            full_name=request.session['full_name'],
            email=request.session['email'],
            mobile=request.session['mobile'],
            address=request.session['address'],
            city=request.session['city'],

ecomprj/templates/core/order-details.html
{% extends 'partials/base.html' %}
{%load static%}
{%block content%}

    <main class="main pages">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Pages <span></span> My Account
                </div>
            </div>
        </div>
        <div class="page-content pt-150 pb-150">
            <div class="container">
                <div class="row">
                    <div class="col-lg-10 m-auto">
                        <div class="row">
                            <div class="col-md-3">
                                <div class="dashboard-menu">
                                    <ul class="nav flex-column" role="tablist">
                                        <li class="nav-item">
                                            <a class="nav-link" id="dashboard-tab" href="{% url 'core:dashboard' %}"><i class="fi-rs-settings-sliders mr-10"></i>Dashboard</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link active" id="orders-tab" data-bs-toggle="tab" href="#orders" role="tab" aria-controls="orders" aria-selected="false"><i class="fi-rs-shopping-bag mr-10"></i>Orders</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="{% url 'userauths:sign-out'%}"><i class="fi-rs-sign-out mr-10"></i>Logout</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-md-9">
                                <div class="tab-content account dashboard-content pl-50">
                                    <div class="tab-pane fade show" id="dashboard" role="tabpanel" aria-labelledby="dashboard-tab">
                                        <div class="card">
                                            <div class="card-header">
                                                <h3 class="mb-0">Hello {{request.user|title}}!</h3>
                                            </div>
                                            <div class="card-body">
                                                <p>
                                                    From your account dashboard. you can easily check &amp; view your <a href="#">recent orders</a>,<br />
                                                    manage your <a href="#">shipping and billing addresses</a> and <a href="#">edit your password and account details.</a>
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="tab-pane active show fade" id="orders" role="tabpanel" aria-labelledby="orders-tab">
                                        <div class="card">
                                            <div class="card-header">
                                                <h3 class="mb-0">Your Orders</h3>
                                            </div>
                                            <div class="card-body">
                                                <div class="table-responsive">
                                                    <table class="table">
                                                        <thead>
                                                            <tr>
                                                                <th>Invoice No</th>
                                                                <th>Item</th>
                                                                <th>Image</th>
                                                                <th>Quantity</th>
                                                                <th>Price</th>
                                                                <th>Total</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            {%for o in order_items%}
                                                            <tr>
                                                                <td>INV-{{o.id}}</td>
                                                                <td>{{o.item}}</td>
                                                                <td class='image product-thumbnail pt-40'><img src={{o.image}}></img></td>
                                                                <td>{{o.qty}}</td>
                                                                <td>${{o.price}}</td>
                                                                <td>${% widthratio o.price 1 o.qty%}</td>                                                            </tr>
                                                            {%endfor%}
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    
{%endblock content%}

ecomprj/templates/core/vendor-list.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content%}

    <main class="main pages mb-80">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Vendors List
                </div>
            </div>
        </div>
        <div class="page-content pt-50">
            <div class="container">
                <div class="archive-header-2 text-center">
                    <h1 class="display-2 mb-50">Vendors List</h1>
                    <div class="row">
                        <div class="col-lg-5 mx-auto">
                            <div class="sidebar-widget-2 widget_search mb-50">
                                <div class="search-form">
                                    <form action="#">
                                        <input type="text" placeholder="Search vendors (by name or ID)..." />
                                        <button type="submit"><i class="fi-rs-search"></i></button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row mb-50">
                    <div class="col-12 col-lg-8 mx-auto">
                        <div class="shop-product-fillter">
                            <div class="totall-product">
                                <p>We have <strong class="text-brand">{{vendors.count}}</strong> vendor{{vendors.count|pluralize}} now</p>
                            </div>
                            <div class="sort-by-product-area">
                                <div class="sort-by-cover mr-10">
                                    <div class="sort-by-product-wrap">
                                        <div class="sort-by">
                                            <span><i class="fi-rs-apps"></i>Show:</span>
                                        </div>
                                        <div class="sort-by-dropdown-wrap">
                                            <span> 50 <i class="fi-rs-angle-small-down"></i></span>
                                        </div>
                                    </div>
                                    <div class="sort-by-dropdown">
                                        <ul>
                                            <li><a class="active" href="#">50</a></li>
                                            <li><a href="#">100</a></li>
                                            <li><a href="#">150</a></li>
                                            <li><a href="#">200</a></li>
                                            <li><a href="#">All</a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="sort-by-cover">
                                    <div class="sort-by-product-wrap">
                                        <div class="sort-by">
                                            <span><i class="fi-rs-apps-sort"></i>Sort by:</span>
                                        </div>
                                        <div class="sort-by-dropdown-wrap">
                                            <span> Featured <i class="fi-rs-angle-small-down"></i></span>
                                        </div>
                                    </div>
                                    <div class="sort-by-dropdown">
                                        <ul>
                                            <li><a class="active" href="#">Mall</a></li>
                                            <li><a href="#">Featured</a></li>
                                            <li><a href="#">Preferred</a></li>
                                            <li><a href="#">Total items</a></li>
                                            <li><a href="#">Avg. Rating</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row vendor-grid">
                    {% for v in vendors%}
                    <div class="col-lg-6 col-md-6 col-12 col-sm-6">
                        <div class="vendor-wrap style-2 mb-40">
                            {% comment %} <div class="product-badges product-badges-position product-badges-mrg">
                                <span class="hot">Mall</span>
                            </div> {% endcomment %}
                            <div class="vendor-img-action-wrap">
                                <div class="vendor-img">
                                    <a href="{% url 'core:vendor-details-page' v.vid%}">
                                        <img class="default-img" src="{{v.image.url}}" alt="" />
                                    </a>
                                </div>
                                <div class="mt-10">
                                    <span class="font-small total-product">{{v.products.count}} Product{{v.products.count|pluralize}}</span>
                                </div>
                            </div>
                            <div class="vendor-content-wrap">
                                <div class="mb-30">
                                    <div class="product-category">
                                        <span class="text-muted">Since {{v.date|date:'Y'}}</span>
                                    </div>
                                    <h4 class="mb-5"><a href="{% url 'core:vendor-details-page' v.vid%}">{{v.title}}</a></h4>
                                    <div class="product-rate-cover">
                                        <div class="product-rate d-inline-block">
                                            <div class="product-rating" style="width: 90%"></div>
                                        </div>
                                        <span class="font-small ml-5 text-muted"> (4.0)</span>
                                    </div>
                                    <div class="vendor-info d-flex justify-content-between align-items-end mt-30">
                                        <ul class="contact-infor text-muted">
                                            <li><img src="assets/imgs/theme/icons/icon-location.svg" alt="" /><strong>Address: </strong> <span>{{v.address}}</span></li>
                                            <li><img src="assets/imgs/theme/icons/icon-contact.svg" alt="" /><strong>Call Us:</strong><span>{{v.contact}}</span></li>
                                        </ul>
                                        <a href="vendor-details-1.html" class="btn btn-xs">Visit Store <i class="fi-rs-arrow-small-right"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% comment %} <div class="pagination-area mt-20 mb-20">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-start">
                            <li class="page-item">
                                <a class="page-link" href="#"><i class="fi-rs-arrow-small-left"></i></a>
                            </li>
                            <li class="page-item"><a class="page-link" href="#">1</a></li>
                            <li class="page-item active"><a class="page-link" href="#">2</a></li>
                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                            <li class="page-item"><a class="page-link dot" href="#">...</a></li>
                            <li class="page-item"><a class="page-link" href="#">6</a></li>
                            <li class="page-item">
                                <a class="page-link" href="#"><i class="fi-rs-arrow-small-right"></i></a>
                            </li>
                        </ul>
                    </nav>
                </div> {% endcomment %}
            </div>
        </div>
    </main>
 
{% endblock content %}